//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDS.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTask
    {
        public int ID { get; set; }
        public string User { get; set; }
        public int Task { get; set; }
        public int Relationship { get; set; }
    
        public virtual TaskRelationship TaskRelationship { get; set; }
        public virtual Task Task1 { get; set; }
    }
}
