//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomDataSet
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TaskCollectorEntities : DbContext
    {
        public TaskCollectorEntities()
            : base("name=TaskCollectorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TaskHit> TaskHits { get; set; }
        public DbSet<TaskRelationship> TaskRelationships { get; set; }
        public DbSet<Task> Tasks { get; set; }
        public DbSet<TaskSource> TaskSources { get; set; }
        public DbSet<TaskVisibility> TaskVisibilities { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<UserTask> UserTasks { get; set; }
    }
}
