//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomDataSet
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.TaskHits = new HashSet<TaskHit>();
            this.UserTasks = new HashSet<UserTask>();
        }
    
        public int ID { get; set; }
        public string EmailAddress { get; set; }
        public string Password { get; set; }
        public System.DateTime CreationTime { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<TaskHit> TaskHits { get; set; }
        public virtual ICollection<UserTask> UserTasks { get; set; }
    }
}
